version: '3.8'

services:
  backend:
    build: ./backend
    container_name: psn-pulse-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - ./backend/env.example:/app/.env:ro
    networks:
      - psn-pulse-network
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: psn-pulse-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - psn-pulse-network
    command: npm run dev -- --host
    restart: unless-stopped

networks:
  psn-pulse-network:
    driver: bridge 